[package]
name = "rmp3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa-sys = "0.3.1"
rodio = "0.17.3"
serde_json = "1.0"
clap = "4.5.3"